CREATE SCHEMA "ROOT";
set schema "ROOT";

    
CREATE TABLE USERS
	(ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
	CONSTRAINT USER_PK PRIMARY KEY,
	
	USERNAME VARCHAR(255) UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL
	);


CREATE TABLE IDENTITIES
    (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    
    DISPLAY_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UID VARCHAR(255)
    
    USER_ID INT CONSTRAINT USER_FK REFERENCES USERS (ID)
    );
