CREATE SCHEMA "ROOT";
set schema "ROOT";

CREATE TABLE IDENTITIES
    (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    
    DISPLAY_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UID VARCHAR(255)
    );

CREATE TABLE USERS
	(USER_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
	CONSTRAINT USER_PK PRIMARY KEY,
	
	USERNAME VARCHAR(255) UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	IDENTITY_ID INT CONSTRAINT USER_FK REFERENCES IDENTITIES (ID) ON DELETE SET NULL
	);
